### ISSUE TITLE
ipa image parsing issue.

### ISSUE THREAD

**Issue by koushik630** [JChord/reiko-parser#1]
ipa build image could not parsing properly. please fix this issue.

**Comment by dos1in** [comment]
@koushik630  try to upgrade to v0.0.8 or can you provide the ipa file ?

**Comment by koushik630** [comment]
we updated to latest version. ipa file you can download from this site. 

https://webapp.diawi.com/install/Tmn88q

**Comment by dos1in** [comment]
ok, I'll check it out.

**Comment by koushik630** [comment]
![ipa_image](https://user-images.githubusercontent.com/13849803/44457874-1074f780-a622-11e8-86c5-2ee794d2b0f3.png)
We attach screenshot above link ipa that is not showing properly in your parser. Please inform when fix this issue. Thank you

**Comment by koushik630** [comment]
hello,
I have implemented your package in my live project. How long take time for this fixes? Please help.
Thanks & Regards 
Koushik Dutta

**Comment by dos1in** [comment]
Hi, @koushik630 this package base in [cgbi-to-png](https://github.com/jakubknejzlik/cgbi-to-png), please track this  [issues](https://github.com/jakubknejzlik/cgbi-to-png/issues/5).

**Comment by koushik630** [comment]
ok.

**Comment by dos1in** [comment]
@koushik630 could you provide original png file from project sources.
