### ISSUE TITLE
Uncaught error when `Info.plist` is corrupt

### ISSUE THREAD

**Issue by awmack** [JChord/reiko-parser#4]
Great utility here! I was doing some testing to see how it handles corrupt packages. One thing I tried was corrupting `Info.plist` within an IPA app file. I simply typed some gibberish into the file header and re-zipped the package. Instead of the error getting passed to my callback, Reiko-Parser crashed. It tried to set `.mobileProvision` on `plistInfo`, which was undefined.

https://github.com/JChord/reiko-parser/blob/7a38dfe0b4516407e3e4d13ef3a9806e917ce388/lib/IpaReader.js#L32 Seems to have returned `undefined` for `plistInfo`, but not thrown an error.

![image](https://user-images.githubusercontent.com/46765488/66768898-b2d4e780-ee81-11e9-953a-1037cfd37fa1.png)

**Comment by JChord** [comment]
fixed v1.0.2
